name: Build and Release Go Project

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Build binary
        run: go build -o bulxy_app .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bulxy_app
          generate_release_notes: true
