name: Build and Release Go Project

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Dashboard
        run: |
          cd web/bluxy-dashboard
          npm install
          npm run build
          cd ../..

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Build binary
        run: go build -o bulxy_app .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bulxy_app
          generate_release_notes: true
